namespace Cards.Core
{
    public enum Card
    {
        Villager = 0,
        Rock = 1,
        Tree = 2,
        BerryBush = 3,
        AppleTree = 10,
        Coin = 8,
        FakeCoin = 22,
        Stone = 4,
        Wood = 5,
        Berry = 6,
        Flint = 7,
        Stick = 9,
        House = 11,
        NewWorldBooster = 12,
        HumbleBeginningsBooster = 13,
        Zone = 14,
        CoinChest = 15,
        Brick = 16,
        Plank = 17,
        CampFire = 18,
        Quarry = 19,
        LumberCamp = 20,
        Garden = 21,
        Cow = 23,
        Milk = 25,
        Chicken = 24,
        Egg = 26,
        Omelette = 27,
        Milkshake = 28,
    }
}
